import Head from "next/head";
import Script from "next/script";
import Navbar from "../components/customs/Navbar";
import PreLoader from "../components/customs/PreLoader";

export default function Home() {
  return (
    <div>
      <Head>
        <title>GBS soft blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="next, app, blog, blogs, my blogs, coders, next blog, gbs, gbs soft, gbs soft blog,website builders, website creator"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="/sc.js" strategy="lazyOnload" />
      <main>
        <Navbar />
      </main>
      <footer></footer>
    </div>
  );
}
